# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "/slack-jekyll-theme" # the subpath of your site, e.g. /blog
url: "url.com" # the base hostname & protocol for your site
alias: username

# Social icons
facebook: username
linkedin: username
github: username
dribbble: username
codepen: username


# Build settings
markdown: kramdown
